[package]
name = "rdbench"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
mpi = { version = "0.8.0", features = ["user-operations", "derive"] }
ndarray = "0.16.1"
